### ISSUE TITLE
Refactor team_repo_permission to make it easier to maintain

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/.github#25]
https://github.com/tinkerbell/.github/blob/master/terraform/repo_team_permission.tf

This is the file where we assign teams to the repo they maintain. I think we can do a better job using modules or for_each but I am not really good with Terraform but @displague is way better!

When this is done and we are happy with the structure I will take the job and create new teams with better ownership of repositories.

**Comment by tstromberg** [comment]
Obsolete. We have since refactored our teams to use the same permissions across repos. 

At some point, we would like to move to a model where permissions are defined by a YAML file - possibly something like https://github.com/kubernetes/community/blob/master/github-management/permissions.md
