### ISSUE TITLE
[Organization/member]: request for micahhausler

### ISSUE THREAD

**Issue by micahhausler** [tinkerbell/.github#35]
### GitHub Username

micahhausler

### Role

Member

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/tinkerbell/proposals/blob/main/proposals/0024/GOVERNANCE.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [tinkerbell-contributors e-mail list](https://groups.google.com/g/tinkerbell-contributors)
- [X] I am actively contributing to 1 or more Tinkerbell subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@detiber

### Sponsor 2

@jacobweinstock

### List of contributions to the Tinkerbell project

* tinkerbell/.github#34 
* tinkerbell/hub#58
* tinkerbell/cluster-api-provider-tinkerbell#65
* tinkerbell/hook#60
* tinkerbell/hook#61
* tinkerbell/hook#62
* tinkerbell/tinkerbell-docs#111
* tinkerbell/tinkerbell-docs#114
* tinkerbell/tinkerbell-docs#115
* tinkerbell/tink#510
* tinkerbell/tink#544
* tinkerbell/tink#542

**Comment by detiber** [comment]
+1 from me

**Comment by jacobweinstock** [comment]
+1 here too!

**Comment by tstromberg** [comment]
+1!

**Comment by tstromberg** [comment]
Your membership invite has been sent out! 🎉
