### ISSUE TITLE
Transfer organizational documents to github.com/tinkerbell/org

### ISSUE THREAD

**Issue by micahhausler** [tinkerbell/.github#37]
Much of the documentation for Tinkerbell was moved to this repo from github.com/tinkerbell/org after tinkerbell/org#1, but as @gianarb stated out:

> We can do it in `.github` but `.github` is a template as well and if I understood how a template works files and directories get moved to all the repositories created from that template. And this is not what I would like

**Narrator**: _`.github` is a template repo_

As it turns out, we don't want everyone opening GH org membership requests on any repo in the Tinkerbell org, so @tstromberg  resurrected the `org` repository.

It now seems obvious to keep the issue templates, label organization in `.github`, but can we move the following items to `org`?

* Code of Conduct
* Communications
* EMERITUS.md

This would effectively make `.github` a place for things that apply to every repo (labels, issue/pr templates, CODEOWNERS, etc) and `org` a place for organizational documents, membership applications, etc.

Current maintainers @mmlb @thebsdbox @tstromberg can you weigh in?

**Comment by thebsdbox** [comment]
That's interesting, if it makes peoples lives easier.. I'm all for it ! :-)

**Comment by mmlb** [comment]
sgtm too.

**Comment by mmlb** [comment]
> **Narrator**: _`.github` is a template repo_

Nit, it isn't actually a _template_ repo, which in github's pov means its used as a starting point for when a new repo is created. The .github repo is just special in that GH uses some of the files from it, sort of like a _parent_ repo (if repos were classes and you were squinting :smile: )

**Comment by mmlb** [comment]
1/2 way done!

**Comment by mmlb** [comment]
:tada:
