### ISSUE TITLE
Contributing: fixed line lengths vs one-sentence-per-line

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/.github#8]
Coming out of discussions in #4.

Going to start it with @displague's verbatim comment and then follow up, hopefully that is the most seamless option.

---
[@displague wrote](https://github.com/tinkerbell/.github/pull/4#issuecomment-682165963):

@mmlb 

We don't have a documentation style-guide in place. I think an issue or PR on that topic would be the best place to have this discussion 😄.

That aside, I don't know which is the more popular opinion [here](https://news.ycombinator.com/item?id=4642395).

I can [link](https://nickjanetakis.com/blog/80-characters-per-line-is-a-standard-worth-sticking-to-even-today) to [posts](https://coderwall.com/p/sgv6aa/markdown-long-urls-that-play-nicely-with-80-character-line-length) [with](https://graphicdesign.stackexchange.com/questions/13724/recommended-column-width-for-text-reading-digital-vs-printed) the [opposite](https://cirosantilli.com/markdown-style-guide/#line-wrapping) [view](https://github.com/carwin/markdown-styleguide#basic-conventions-for-markdown-files) point on [readability](https://www.viget.com/articles/the-line-length-misconception/) and fixed-length lines. License files (markdown or others) tend to carry the 80 character column width. I encounter and use the [Markdown Linter](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length) in many places, including [VS Code](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).

In my HTML editing days, I preferred one *paragraph* per line, and I preferred using the IDE to soft-break text.

My preference changed when I started working with Go and Markdown, especially in Github where the review pane needs to be horizontally scrolled beyond 80 characters (_Update: no longer the case?_ 🤔).  The viewer or maintainer is not always behind an editor or IDE where width settings can be controlled.

The column width changes nothing for readers of the rendered documents. This mostly affects the people that manage and review documents.

Would it help if I adopted the citation style of markdown links? _(Update: Applied)._
 <http://www.rubycoloredglasses.com/2017/11/markdown-links-80-character-line-length/>

**Comment by mmlb** [comment]
> 
> That aside, I don't know which is the more popular opinion [here](https://news.ycombinator.com/item?id=4642395).


The linked article is *actually* about semantic-line-feeds (slf), not one-sentence-per-line (ospl). IMO semantic-line-feeds are not worth the pain.

I think we would be best off with [plain english](http://www.plainenglish.co.uk/how-to-write-in-plain-english.html)([discussion](https://news.ycombinator.com/item?id=24268382)) for the content, best expressed with ospl. By striving towards plain-english lines, we would naturally have shorter sentences.

Let me pick through some of the links you mentioned:

> I can [link](https://nickjanetakis.com/blog/80-characters-per-line-is-a-standard-worth-sticking-to-even-today)

These are good points but being choosy, 80cols was a monitor limitation and is being argued here to continue it, just with "virtual" monitors basically. I do take issue with noting 40char difference, yet the file browser is open all the time and taking quite a bit of horizontal screen space. A good point is brought up here though, "I don’t know about you but I find it much easier to read code when the lines aren’t miles long.", that is something that ospl actually helps with since you'll see how things go off to then end and prod you reword. This is better for both source and the final rendering because its the *content* that was long that actually matters, not how its stored in source.

This feels like the most biased sourced and my response shows mine too :D.

> [posts](https://coderwall.com/p/sgv6aa/markdown-long-urls-that-play-nicely-with-80-character-line-length)

Agree, lets do reference type URL links. This seems like it can only be a good thing.

> [with](https://graphicdesign.stackexchange.com/questions/13724/recommended-column-width-for-text-reading-digital-vs-printed)

This is anti-fixed length. ospl gets you to think about each sentence when writing it. If your one sentence is 200chars in source its going to be 200chars in output and its going to be hard to read. Wrapping it in source at 80chars is not going to make it easier to read in final form.

> the [opposite](https://cirosantilli.com/markdown-style-guide/#line-wrapping) 

This seems to support ospl :+1:.

> [view](https://github.com/carwin/markdown-styleguide#basic-conventions-for-markdown-files)

No real explanation, I'll chalk this up to cargo culting.

> point on [readability](https://www.viget.com/articles/the-line-length-misconception/) and fixed-length lines.

Against line length limits.

> License files (markdown or others) tend to carry the 80 character column width. I encounter and use the [Markdown Linter](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md?rgh-link-date=2020-08-27T20%3A09%3A51Z#md013---line-length) in many places, including [VS Code](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).

Configurable (editorconfig) :D.

> In my HTML editing days, I preferred one _paragraph_ per line, and I preferred using the IDE to soft-break text.

Yep I've heard about that, but I think one sentence is better. We can break down and analyze the grammar, spelling, sentiment down to the sentence. We can't really go lower (slf can but I think is too low level, also runs against plain-english). Source code equivalent would be multiple statements per line :scream:!

> My preference changed when I started working with Go and Markdown, especially in Github where the review pane needs to be horizontally scrolled beyond 80 characters (_Update: no longer the case?_ thinking).

Looks like its a 105chars now (at least on my screen).

> The viewer or maintainer is not always behind an editor or IDE where width settings can be controlled.

OSPL is simple rule to go with and works in the browser too :D.

> The column width changes nothing for readers of the rendered documents. This mostly affects the people that manage and review documents.

OSPL helps to point out and make obvious when a sentence is too long and would make the rendered document harder to read/parse.

> 
> Would it help if I adopted the citation style of markdown links? _(Update: Applied)._
> [http://www.rubycoloredglasses.com/2017/11/markdown-links-80-character-line-length](http://www.rubycoloredglasses.com/2017/11/markdown-links-80-character-line-length/)

Yes, definitely.

**Comment by mmlb** [comment]
[@DailyAlice wrote](https://github.com/tinkerbell/.github/pull/4#issuecomment-686530023):

> Please do [one-sentence-per-line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line). I like to read markdown in source form and this layout makes it quite difficult.

As someone who also likes to read the markdown source, I find one sentence per line more difficult to read. I'm fine with the 80 column-width or with no fixed column-width. But reading something that is one-sentence per line is very difficult.

**Comment by mmlb** [comment]
> [@DailyAlice wrote](https://github.com/tinkerbell/.github/pull/4#issuecomment-686530023):
> 
> > Please do [one-sentence-per-line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line). I like to read markdown in source form and this layout makes it quite difficult.
> 
> As someone who also likes to read the markdown source, I find one sentence per line more difficult to read. I'm fine with the 80 column-width or with no fixed column-width. But reading something that is one-sentence per line is very difficult.

I sort of feel the same way. Reading wrapped text flows better in source. But when review/writing I find it best to consider each sentence. Looking at the diffs, grammar, spelling, content feels easier when giving more attention to the sentence.

If flowing through the paragraph is not working too well when trying to review the whole paragraph I then go over to the rendered. Gives me the best of both worlds.

**Comment by mmlb** [comment]
I guess this issue also opens up the question of if we should try to write our docs in "plain english" too. I think it makes particular sense for docs where having to wrangle the structure of a sentence can take away from grok'ing the concept.

**Comment by tstromberg** [comment]
For what it's worth on my end -- having character limits in any coded language (markdown, html, go, yaml) makes diff output and code review significantly easier with today's tools (github, `diff`). I am not picky on whatever we set the limit to, but we should probably have the linting tool setup appropriately.

@mmlb - is there a line length limit for markdown that you would feel comfortable with?

**Comment by mmlb** [comment]
> @mmlb - is there a line length limit for markdown that you would feel comfortable with?

Not particularly, what ever feels wrong :(. I think this is more of a sylistic vs hard rule thing. Long lines might be better of being re written to be shorter or plain (as in https://en.wikipedia.org/wiki/Plain_English)

**Comment by tstromberg** [comment]
Discussed in triage: One sentence per line is interesting to make authoring issues more obvious, but difficult to implement at this time due to the lack of linting support.
